package com.oracle.xmlns.scheduler;

import javax.xml.ws.BindingProvider;

import com.pradipta.handler.WSSecurityHeaderSOAPHandler;

import javax.xml.ws.handler.Handler;
import javax.xml.ws.Binding;
import javax.xml.ws.BindingProvider;

import java.util.ArrayList;
import java.util.List;

import java.util.Map;

import javax.xml.ws.handler.soap.SOAPHandler;
import javax.xml.ws.handler.soap.SOAPMessageContext;

import weblogic.wsee.jws.jaxws.owsm.SecurityPoliciesFeature;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.1.3.0.0.1008
public class SchedulerServiceImplPortClient {
    public static void main(String[] args) {
        ESSWebService_Service eSSWebService_Service = new ESSWebService_Service();

        // Configure security feature
        SecurityPoliciesFeature securityFeatures = new SecurityPoliciesFeature(new String[] {
                                                                               "oracle/wss_username_token_client_policy" });
        ESSWebService eSSWebService = eSSWebService_Service.getSchedulerServiceImplPort(securityFeatures);
        // Add your code to call the desired methods.

        try {
            BindingProvider bindingProvider = (BindingProvider) eSSWebService;
            @SuppressWarnings("rawtypes")
            WSSecurityHeaderSOAPHandler soapHandlerAuthentication =
                new WSSecurityHeaderSOAPHandler("weblogic", "welcome1");
            Binding binding = bindingProvider.getBinding();
            List<Handler> handlerList = binding.getHandlerChain();
            handlerList.add(soapHandlerAuthentication);
            binding.setHandlerChain(handlerList);
            Map<String, Object> reqContext = ((BindingProvider) eSSWebService).getRequestContext();
            reqContext.put(BindingProvider.USERNAME_PROPERTY, "weblogic");
            reqContext.put(BindingProvider.PASSWORD_PROPERTY, "welcome1");
            eSSWebService.holdRequest(33787);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}
