
package com.pradipta.hsf.customwebservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebService(name = "CustomHSFWebService", targetNamespace = "http://pradipta.com/hsf/customwebservices/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface CustomHSFWebService {


    /**
     *
     * @param request
     * @return
     *     returns com.pradipta.hsf.customwebservices.GetEntityDataCellsResponse
     * @throws GetEntityDataCellsFault_Exception
     */
    @WebMethod(action = "http://pradipta.com/hsf/customwebservices//getEntityDataCells")
    @WebResult(name = "getEntityDataCellsResponse", targetNamespace = "http://pradipta.com/hsf/customwebservices/",
               partName = "response")
    public GetEntityDataCellsResponse getEntityDataCells(@WebParam(name = "getEntityDataCellsRequest",
                                                                   targetNamespace =
                                                                   "http://pradipta.com/hsf/customwebservices/",
                                                                   partName = "request")
                                                         GetEntityDataCellsRequest request) throws GetEntityDataCellsFault_Exception;

}
