
package com.pradipta.hsf.customwebservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebFault(name = "getEntityDataCellsFault", targetNamespace = "http://pradipta.com/hsf/customwebservices/")
public class GetEntityDataCellsFault_Exception extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     *
     */
    private GetEntityDataCellsFault faultInfo;

    /**
     *
     * @param message
     * @param faultInfo
     */
    public GetEntityDataCellsFault_Exception(String message, GetEntityDataCellsFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @param message
     * @param faultInfo
     * @param cause
     */
    public GetEntityDataCellsFault_Exception(String message, GetEntityDataCellsFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @return
     *     returns fault bean: com.pradipta.hsf.customwebservices.GetEntityDataCellsFault
     */
    public GetEntityDataCellsFault getFaultInfo() {
        return faultInfo;
    }

}
