<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ImportHSFdata"
     targetNamespace="http://pbcs.pradipta.com/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://pbcs.pradipta.com/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="PBCS_RestServices_Component.test">
        <plnk:role name="ImportHSFdata" portType="tns:ImportHSFdata"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://pbcs.pradipta.com/" location="ImportHSFdata.wsdl"/>
</wsdl:definitions>
